export const FETCH_COMPANIES_REQUEST = "FETCH_COMPANIES_REQUEST";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const FETCH_COMPANIES_FAILURE = "FETCH_COMPANIES_FAILURE";
export const FILTER_COMPANIES = "FILTER_COMPANIES"
export const GET_AVG_RATING = "GET_AVG_RATING"