export const FETCH_COMPANIES_REQUEST = "FETCH_COMPANIES_REQUEST";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const FETCH_COMPANIES_FAILURE = "FETCH_COMPANIES_FAILURE";
export const FILTER_COMPANIES = "FILTER_COMPANIES"
export const SET_COMPANY_ID = "SET_COMPANY_ID"