export const FETCH_ALLSCHEDULES_REQUEST = "FETCH_ALLSCHEDULES_REQUEST";
export const FETCH_ALLSCHEDULES_SUCCESS = "FETCH_ALLSCHEDULES_SUCCESS";
export const FETCH_ALLSCHEDULES_FAILURE = "FETCH_ALLSCHEDULES_FAILURE";
export const UPDATE_ALLSCHEDULES_COMMENT = "UPDATE_ALLSCHEDULES_COMMENT";