export const FETCH_SCHEDULES_REQUEST = "FETCH_SCHEDULES_REQUEST";
export const FETCH_SCHEDULES_SUCCESS = "FETCH_SCHEDULES_SUCCESS";
export const FETCH_SCHEDULES_FAILURE = "FETCH_SCHEDULES_FAILURE";

export const POST_SCHEDULE = "POST_SCHEDULE";
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const CANCEL_SCHEDULE = "CANCEL_SCHEDULE";